### ISSUE TITLE
Missing tags (4.38.3 and 4.38.4) on docker hub

### ISSUE THREAD

**Issue by SIkebe** [gitbucket/gitbucket-docker#50]
I can't find 4.38.3 and 4.38.4 on docker hub. @takezoe Do you know something?
https://hub.docker.com/r/gitbucket/gitbucket/tags
![image](https://user-images.githubusercontent.com/17608272/202890099-b64dfdae-a20a-475d-bdd9-cede93a9e3e4.png)

**Comment by takezoe** [comment]
Hmm, not sure why.

**Comment by takezoe** [comment]
Maybe tag has been fixed as `gitbucket/gitbucket` since https://github.com/gitbucket/gitbucket-docker/pull/43.

**Comment by takezoe** [comment]
Merged #51 and recreated 4.38.4 tag. Though 4.38.3 is still missing on DockerHub, it should be okay as 4.38.3 has known issues so it should be avoided to use.

<img width="1332" alt="Screen Shot 2022-12-25 at 12 42 00" src="https://user-images.githubusercontent.com/1094760/209456297-086cfd0e-68bf-4f20-8f51-a1163f11938d.png">
