### ISSUE TITLE
Moving the repository to gitbucket group repository?

### ISSUE THREAD

**Issue by takumaw** [gitbucket/gitbucket-docker#8]
This, too, is not exactly an issue, but it's better moving this repository to the official Gitbucket group repository (because it is practically the official docker image of Gitbucket.)

Before moving, we also need to make this docker image to be aligned with commons practices of making Docker images, like applying #7.

**Comment by takezoe** [comment]
Hmm... This image isn't the official docker image. You can find a well-downloaded and well-maintained docker image more than this image at DockerHub:
https://hub.docker.com/r/f99aq8ove/gitbucket/

Fortunately, this image has been maintained by pull requests from some users, but actually it was just my training for writing Dockerfile hehe.

**Comment by aadrian** [comment]
@takumaw https://github.com/gitbucket/gitbucket/wiki/Docker
